@url = http://localhost:8080/api/alias

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "name": "Marc",
    "persona": "Student",
    "agentId": 1
}

###

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "name": "Marc",
    "persona": "",
    "agentId": 1
}

###
PUT {{url}}/1 HTTP/1.1
Content-Type: application/json

{
    "aliasId": 1,
    "name": "John",
    "persona": "chef",
    "agentId": "2"

}

###

DELETE {{url}}/1 HTTP/1.1